# Generated by Django 5.0.6 on 2024-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_detalle',
            name='pk_carritodet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
