# Generated by Django 5.0.6 on 2024-10-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_carrito_detalle_pk_carritodet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='productos')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagenes', to='App.productos')),
            ],
        ),
    ]
