# Generated by Django 5.0.6 on 2024-12-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precioreb_producto',
        ),
    ]
